# Generated by Django 5.1.3 on 2025-01-08 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='user',
        ),
    ]
